Repository kids-first/kf-somatic-workflow, pull requests merged in 2021-05, with the labels that each got.

#116 ✨ Nhj consensus contigs
  scripts/consensus_merge.py
Labels: bix-dev, enhancement

#122 🐛 etool type workaround sbg errors
  tools/expression_flatten_list.cwl
  workflow/kfdrc-somatic-variant-workflow.cwl
Labels: bix-dev, bug

#123 🖼 pretty cnvkit pictures
  sub_workflows/kfdrc_cnvkit_sub_wf.cwl
  tools/gatk_filter_germline_variant.cwl
  workflow/kfdrc-somatic-variant-workflow.cwl
  workflow/kfdrc_production_cnvkit_wf.cwl
Labels: bix-dev, enhancement

#125 ✏️ adjust final output name
  workflow/kfdrc_consensus_calling.cwl
Labels: bix-dev, bug

#126 🌯 Somatic WF Release 3.0
  README.md
  docs/kfdrc-somatic-variant-workflow.cwl.png
  docs/kfdrc-somatic-variant-workflow.png
  docs/kfdrc_lancet_sub_wf.cwl.png
  docs/kfdrc_lancet_sub_wf.md
  docs/kfdrc_mutect2_sub_wf.md
  docs/kfdrc_strelka2_subworkflow.md
  docs/kfdrc_vardict_sub_wf.md
  sub_workflows/kfdrc_cnvkit_sub_wf.cwl
  tools/cnvkit_batch.cwl
  workflow/kfdrc-somatic-variant-workflow.cwl
  workflow/kfdrc_production_cnvkit_wf.cwl
Labels: bix-dev, documentation, feature request
