Repository kids-first/kf-somatic-workflow, pull requests merged in 2021-03, with the labels that each got.

#85 🎭 Germline masking tools
  tools/bcftools_annotate.cwl
  tools/gatk_variant_filter.cwl
Labels: feature request

#88 place output in . and fix output basename
  scripts/consensus_merge.py
Labels: bug

#87 Nhj strelka2 fields tool
  tools/add_strelka2_fields.cwl
Labels: enhancement

#90 🐛 b allele truly optional
  README.md
  tools/tabix_index.cwl
  workflow/kfdrc-somatic-variant-workflow.cwl
Labels: bug

#92 ✨ made callers for consensus optional w/ default 2
  scripts/consensus_merge.py
Labels: enhancement

#89 🔧 fixed/clarified theta2 subwf name
  sub_workflows/kfdrc_run_theta2_sub_wf.cwl
Labels: documentation

#91 🔧 update hotspots script
  scripts/hotspot.py
Labels: enhancement

#93 ✨ add hotspot tool
  tools/hotspots_annotation.cwl
Labels: enhancement

#94 :sparkles: CWL tool for consensus script
  tools/consensus_merge.cwl
Labels: enhancement

#96 :bug: assign to alleles, avoid INFO END
  scripts/consensus_merge.py
Labels: bug

#95 📦 Created a subwf to reformat existing caller outputs and …
  dev/temp_norm_annot_patch_wf.cwl
  sub_workflows/kfdrc_annot_vcf_sub_wf.cwl
  tools/add_strelka2_fields.cwl
  tools/generic_rename_outputs.cwl
  tools/vep_somatic_annotate_r93.cwl
Labels: feature request

#98 ✨ Consensus workflow update
  workflow/kfdrc_consensus_calling.cwl
Labels: enhancement

#97 🔥 hotspot logic
  scripts/hotspot.py
Labels: enhancement
