Repository kids-first/kf-somatic-workflow, pull requests merged in 2021-04, with the labels that each got.

#101 🐛 update suggested file paths
  workflow/kfdrc-somatic-variant-workflow.cwl
Labels: bug

#100 🍌 split protein input
  tools/hotspots_annotation.cwl
Labels: bix-dev, enhancement

#106 🔧 Hotspot -> HotSpotAllele
  scripts/consensus_merge.py
Labels: bix-dev, bug

#104 ✨ Nhj public output
  workflow/kfdrc_consensus_calling.cwl
Labels: bix-dev, enhancement

#107 🐳 point at updated docker
  tools/theta2_purity.cwl
Labels: bix-dev, bug

#112 🔨 made a potentially problematic input optional
  dev/delme_pbta_temp_vcftomaf.cwl
  dev/delme_tcga_temp_vcftomaf.cwl
  dev/delme_temp_vcftomaf.cwl
  tools/kf_mskcc_vcf2maf.cwl
Labels: bix-dev, bug
